language: android
jdk: oraclejdk8
sudo: false
android:
    components:
        - tools
        - build-tools-25.0.0
        - android-25
        - extra-android-m2repository
        - platform-tools
script:
    - cd opacclient
    - ./gradlew check lint test jacocoRootReport coveralls
    - cat opacapp/build/outputs/lint-results-debug.xml
cache:
    directories:
        - $HOME/.gradle
