language: android
jdk: oraclejdk8
sudo: false
android:
    components:
        - tools
        - build-tools-25.0.2
        - android-25
        - extra-android-m2repository
        - platform-tools
script:
    - cd opacclient
    - ./gradlew check lint test jacocoRootReport coveralls
    - cat opacapp/build/reports/lint-results.xml
cache:
    directories:
        - $HOME/.gradle
