language: android
jdk: oraclejdk8
sudo: false
android:
    components:
        - tools
        - build-tools-24.0.0
        - android-24
        - extra-android-m2repository
script:
    - cd opacclient
    - ./gradlew check lint test
cache:
    directories:
        - $HOME/.gradle
